version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql

  redis:
    container_name: my-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data/:/data

  consul1:
    image: hashicorp/consul:latest
    container_name: consul1
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600"
    command: [ "agent", "-server", "-bootstrap-expect=1", "-ui", "-bind=0.0.0.0", "-client=0.0.0.0" ]
    restart: unless-stopped
#  consul2:
#    image: hashicorp/consul
#    container_name: node2
#    #要有一个加入的步骤
#    command: agent -retry-join=consul1 -node=node2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
#    #要依赖谁
#    depends_on:
#      - consul1
#
#  consul3:
#    image: hashicorp/consul
#
#    container_name: node3
#    #要有一个加入的步骤
#    command: agent -retry-join=consul1 -node=node3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
#    #要依赖谁
#    depends_on:
#      - consul1

#  #有一个consul需要拿出来做ui
#  consul4:
#    image: hashicorp/consul
#    container_name: node4
#    #要有一个加入的步骤,制作ui
#    command: agent -retry-join=consul1 -node=node4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
#    #暴露在哪里
#    ports:
#      - "8500:8500"
#    #要依赖谁
#    depends_on:
#      - consul2
#      - consul3
